export const urlbdr = 'https://recetas-demoday.herokuapp.com/recetas'
export const urlchef = 'https://recetas-demoday.herokuapp.com/recetaIndividual'
export const urlsocial = 'https://recetas-demoday.herokuapp.com/zonaSocial'
export const urlciudades = 'https://recetas-demoday.herokuapp.com/ciudades'
export const urlRD = 'https://calendario-recetas.herokuapp.com/desayuno'
export const urlRA = 'https://calendario-recetas.herokuapp.com/almuerzo'
export const urlRC = 'https://calendario-recetas.herokuapp.com/cena'
